name: Rust

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make
    - name: Run tests
      run: make check

  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install rust
      run: brew install rust
    - name: Build
      run: make
    - name: Run tests
      run: make check
